---
- name: "Display if architecture is not supported"
  ansible.builtin.debug:
    msg: "{{ ansible_architecture }} architecture is not supported"
  when: ansible_architecture not in supported_architectures

- name: "Skip role if architecture is not supported"
  ansible.builtin.meta: end_play
  when: ansible_architecture not in supported_architectures

- name: "Check if distro is in supported distros list"
  ansible.builtin.set_fact:
    distro_supported: false
  when: supported_distros | selectattr("name", "equalto", ansible_distribution) | list | length == 0

- name: "Check if distro version is supported"
  ansible.builtin.set_fact:
    distro_supported: false
  loop: "{{ supported_distros }}"
  when: >
    ansible_distribution == item.name and
    ansible_distribution_version is version(item.min_version, "<")

- name: "Display if distro is not supported"
  ansible.builtin.debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} is not supported"
  when: distro_supported is false

# For molecule testing only
- name: "Create file if distro is not supported"
  ansible.builtin.copy:
    dest: "/tmp/unsupported_distro"
    content: "unsupported"
    mode: "0644"
  no_log: true
  when: distro_supported is false and "molecule-notest" in ansible_skip_tags

- name: "Skip role if distro is not supported"
  ansible.builtin.meta: end_play
  when: distro_supported is false
