---
- name: "Ensure /usr/share/keyrings/nodesource.gpg is removed"
  ansible.builtin.file:
    path: /usr/share/keyrings/nodesource.gpg
    state: absent

- name: "Remove NodeSource GPG key from APT keyring"
  ansible.builtin.apt_key:
    id: "68576280"
    state: absent

- name: "Ensure /etc/apt/sources.list.d/nodesource.list is removed"
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/nodesource.list
    state: absent

- name: "Ensure /etc/apt/signing-key-nodesource-repo.asc is removed"
  ansible.builtin.file:
    path: /etc/apt/signing-key-nodesource-repo.asc
    state: absent

- name: "Find all Node.js list repository files"
  ansible.builtin.find:
    paths: "/etc/apt/sources.list.d"
    patterns: "deb_nodesource_com_node_*_x.list"
  register: files_to_remove

- name: "Ensure all Node.js list repository files are tidied up"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ files_to_remove.files }}"

- name: "Find all Node.js sources repository files"
  ansible.builtin.find:
    paths: "/etc/apt/sources.list.d"
    patterns: "nodesource-*x.sources"
  register: files_to_remove

- name: "Ensure all Node.js sources repository files are tidied up"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ files_to_remove.files }}"
