---
- name: "Gather facts"
  ansible.builtin.setup:
  when: ansible_facts|default({}) == {}

- name: "Ensure architecture is supported"
  ansible.builtin.fail:
    msg: "Unsupported architecture"
  when: ansible_architecture not in ['x86_64', 'aarch64', 'armv7l']

- name: "Cleanup (Debian Family)"
  ansible.builtin.include_tasks: cleanup-Debian.yml
  when: ansible_os_family == "Debian"

- name: "Configure repository (Debian Family)"
  ansible.builtin.include_tasks: repo-Debian.yml
  when: ansible_os_family == "Debian"

- name: "Install"
  ansible.builtin.include_tasks: install.yml
