---
- name: "Gather facts"
  ansible.builtin.setup:
  when: ansible_facts|default({}) == {}

- name: "Ensure architecture is supported"
  ansible.builtin.fail:
    msg: "Unsupported architecture"
  when: ansible_architecture not in ['x86_64', 'aarch64', 'armv7l']

- name: "Check if distro version is supported"
  ansible.builtin.meta: end_play
  when:
    - (ansible_os_family == 'RedHat' and ansible_distribution_version is version('6', '<=')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('18.04', '<='))

- name: "Ensure Node.js requirements are installed"
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - python3-debian
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: "Release detection"
  ansible.builtin.include_tasks: release-detection.yml
  when: nodejs_version == "current" or nodejs_version == "lts"

- name: "Cleanup (Debian Family)"
  ansible.builtin.include_tasks: cleanup-Debian.yml
  when: ansible_os_family == "Debian"

- name: "Configure repository (Debian Family)"
  ansible.builtin.include_tasks: repo-Debian.yml
  when: ansible_os_family == "Debian"

- name: "Install"
  ansible.builtin.include_tasks: install.yml
  when: nodejs_state == "present"

- name: "Remove"
  ansible.builtin.include_tasks: remove.yml
  when: nodejs_state == "absent"
