---
- name: "Ensure Node.js requirements are installed (apt)"
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - python3-debian
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: ansible_pkg_mgr == "apt"

- name: "Ensure rpm-python is installed (dnf)"
  ansible.builtin.dnf:
    name: python3-rpm
    state: present
    update_cache: true
  when: ansible_pkg_mgr == "dnf"
