---
- name: "Ensure Node.js is removed (apt)"
  ansible.builtin.apt:
    name: nodejs
    state: absent
  when: ansible_pkg_mgr == "apt"

- name: "Ensure Node.js is removed (dnf)"
  ansible.builtin.dnf:
    name: nodejs
    state: absent
  when: ansible_pkg_mgr == "dnf"
