---
- name: "Ensure Node.js is removed (apt)"
  ansible.builtin.apt:
    name: nodejs
    state: absent
    update_cache: true
    cache_valid_time: 3600
  when: ansible_pkg_mgr == "apt"

- name: "Ensure Node.js is removed (yum)"
  ansible.builtin.yum:
    name: nodejs
    state: absent
  when: ansible_pkg_mgr == "yum"

- name: "Ensure Node.js is removed (dnf)"
  ansible.builtin.yum:
    name: nodejs
    state: absent
  when: ansible_pkg_mgr == "dnf"
