---
- name: "Install Node.js from distro repos"
  when: nodejs_version == "distro" or nodejs_state == "absent"
  block:
    - name: "Gather package facts"
      ansible.builtin.package_facts:
        manager: auto

    - name: "Set if Node.js is installed"
      ansible.builtin.set_fact:
        nodejs_installed: ansible_facts.packages is defined and 'nodejs' in ansible_facts.packages

    - name: "Set installed Node.js version"
      ansible.builtin.set_fact:
        installed_nodejs_version: "{{ ansible_facts.packages['nodejs'][0].version.split('.')[0] }}"
      when: nodejs_installed and 'nodejs' in ansible_facts.packages

    - name: "Display installed Node.js version"
      ansible.builtin.debug:
        msg: "{{ 'Node.js ' + installed_nodejs_version + ' is installed' if installed_nodejs_version is defined and installed_nodejs_version != '' else 'Node.js is not installed' }}"

    - name: "Ensure NodeSource repository is removed for Node.JS {{ nodejs_version }}"
      ansible.builtin.deb822_repository:
        name: "nodesource"
        uris: "https://deb.nodesource.com/node_{{ nodejs_version }}.x"
        signed_by: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        suites: nodistro
        components: main
        state: absent
        enabled: true
      notify:
        - "Update apt cache (Debian Family)"
        - "Remove Node.JS"

    - name: "Ensure nsolid preferences are removed"
      ansible.builtin.file:
        path: /etc/apt/preferences.d/nsolid
        state: absent
      notify:
        - "Update apt cache (Debian Family)"
        - "Remove Node.JS"

    - name: "Ensure Node.js preferences are removed"
      ansible.builtin.file:
        path: /etc/apt/preferences.d/nodejs
        state: absent
      notify:
        - "Update apt cache (Debian Family)"
        - "Remove Node.JS"

    - name: "Flush handlers"
      ansible.builtin.meta: flush_handlers

    - name: "Check available Node.js version in the repository"
      ansible.builtin.command:
        cmd: "apt-cache policy nodejs"
      changed_when: false
      register: aptcache

    - name: "Set available Node.js version"
      ansible.builtin.set_fact:
        available_nodejs_version: "{{ aptcache.stdout_lines[2].split(':')[1].strip().split(' ')[0].split('.')[0] }}"

    - name: "Display available Node.js version to install"
      ansible.builtin.debug:
        msg: "Node.js {{ available_nodejs_version }} is available to install"

- name: "Install Node.js from NodeSource"
  when: nodejs_version != "distro" and nodejs_state == "present"
  block:
    - name: "Gather package facts"
      ansible.builtin.package_facts:
        manager: auto

    - name: "Set if Node.js is installed"
      ansible.builtin.set_fact:
        nodejs_installed: ansible_facts.packages is defined and 'nodejs' in ansible_facts.packages

    - name: "Set installed Node.js version"
      ansible.builtin.set_fact:
        installed_nodejs_version: "{{ ansible_facts.packages['nodejs'][0].version.split('.')[0] }}"
      when: nodejs_installed and 'nodejs' in ansible_facts.packages

    - name: "Display installed Node.js version"
      ansible.builtin.debug:
        msg: "{{ 'Node.js ' + installed_nodejs_version + ' is installed' if installed_nodejs_version is defined and installed_nodejs_version != '' else 'Node.js is not installed' }}"

    - name: "Ensure NodeSource repository is added for Node.JS {{ nodejs_version }}"
      ansible.builtin.deb822_repository:
        name: "nodesource"
        uris: "https://deb.nodesource.com/node_{{ nodejs_version }}.x"
        signed_by: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        suites: nodistro
        components: main
        state: present
        enabled: true
      notify:
        - "Update apt cache (Debian Family)"
        - "Remove Node.JS"

    - name: "Ensure nsolid preferences are set"
      ansible.builtin.copy:
        dest: /etc/apt/preferences.d/nsolid
        content: |
          Package: nsolid
          Pin: origin deb.nodesource.com
          Pin-Priority: 600
        owner: root
        group: root
        mode: "0644"
      notify:
        - "Update apt cache (Debian Family)"
        - "Remove Node.JS"

    - name: "Ensure nodejs preferences are set"
      ansible.builtin.copy:
        dest: /etc/apt/preferences.d/nodejs
        content: |
          Package: nodejs
          Pin: origin deb.nodesource.com
          Pin-Priority: 600
        owner: root
        group: root
        mode: "0644"
      notify:
        - "Update apt cache (Debian Family)"
        - "Remove Node.JS"

    - name: "Flush handlers"
      ansible.builtin.meta: flush_handlers

    - name: "Check available Node.js version in the repository"
      ansible.builtin.command:
        cmd: "apt-cache policy nodejs"
      changed_when: false
      register: aptcache

    - name: "Set available Node.js version"
      ansible.builtin.set_fact:
        available_nodejs_version: "{{ aptcache.stdout_lines[2].split(':')[1].strip().split(' ')[0].split('.')[0] }}"

    - name: "Display available Node.js version to install"
      ansible.builtin.debug:
        msg: "Node.js {{ available_nodejs_version }} is available to install"
