---
- name: "Ensure Node.js requirements are installed"
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - python3-debian
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "Ensure repository is added for Nodejs {{ nodejs_version }}"
  ansible.builtin.deb822_repository:
    name: "nodesource"
    uris: "https://deb.nodesource.com/node_{{ nodejs_version }}"
    signed_by: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    suites: nodistro
    components: main
    state: present
    enabled: true
  notify: "Update apt cache (Debian Family)"

- name: "Ensure nsolid preferences are set"
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/nsolid
    content: |
      Package: nsolid
      Pin: origin deb.nodesource.com
      Pin-Priority: 600
    owner: root
    group: root
    mode: "0644"
  notify: "Update apt cache (Debian Family)"

- name: "Ensure nodejs preferences are set"
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/nodejs
    content: |
      Package: nodejs
      Pin: origin deb.nodesource.com
      Pin-Priority: 600
    owner: root
    group: root
    mode: "0644"
  notify: "Update apt cache (Debian Family)"

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
